Server side regridding with Polytope

In [15]:
import earthkit.data

In [ ]:
request_original = {
        "class": "d1",
        "expver": "0001",
        "stream": "oper",
        "dataset": "extremes-dt",
        "date": "-14",
        "time": "0000",
        "type": "fc",
        "levtype": "sfc",
        "step": "0",
        "param": "167",
        "grid": "av" #retrieve original archived grid
    }
original_grid = earthkit.data.from_source("polytope", "destination-earth", request_original, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

In [3]:
original_grid.ls() # display original grid, in this case it will be reduced_gg

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,2t,heightAboveGround,2,20250813,0,0,fc,None,reduced_gg

Lat/Lon Regriding

In [29]:
request_lat_lon = {
        "class": "d1",
        "expver": "0001",
        "stream": "oper",
        "dataset": "extremes-dt",
        "date": "-14",
        "time": "0000",
        "type": "fc",
        "levtype": "sfc",
        "step": "0",
        "param": "167",
        "grid": "0.1/0.1" #lon/lat value
    }
lat_lon_grid = earthkit.data.from_source("polytope", "destination-earth", request_lat_lon, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

2025-08-27 14:45:27 - INFO - Key read from /Users/maes/.polytopeapirc
2025-08-27 14:45:27 - INFO - Sending request...
{'request': 'class: d1\n'
            'dataset: extremes-dt\n'
            "date: '-14'\n"
            "expver: '0001'\n"
            'grid: 0.1/0.1\n'
            'levtype: sfc\n'
            "param: '167'\n"
            "step: '0'\n"
            'stream: oper\n'
            "time: '0000'\n"
            'type: fc\n',
 'verb': 'retrieve'}
2025-08-27 14:45:27 - INFO - Polytope user key found in session cache for user maes
2025-08-27 14:45:29 - INFO - Request accepted. Please poll ./5ee1faed-b603-410f-9f8f-c57997570489 for status
2025-08-27 14:45:29 - INFO - Polytope user key found in session cache for user maes
2025-08-27 14:45:29 - INFO - Checking request status (5ee1faed-b603-410f-9f8f-c57997570489)...
2025-08-27 14:46:44 - WARNING - Recovering from connection error.
HTTPSConnectionPool(host='polytope.lumi.apps.dte.destination-earth.eu', port=443): Max retries exceeded with url: /api/v1/requests/5ee1faed-b603-410f-9f8f-c57997570489 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x166b53d90>, 'Connection to polytope.lumi.apps.dte.destination-earth.eu timed out. (connect timeout=None)'))
2025-08-27 14:46:44 - INFO - Attempt 1 of 10
2025-08-27 14:46:44 - INFO - Next retry in 120 seconds
2025-08-27 14:48:45 - INFO - The current status of the request is 'processed'

In [22]:
lat_lon_grid.ls() # grid now in lat/lon

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,2t,heightAboveGround,2,20250813,0,0,fc,None,regular_ll

In [ ]:
request_healpix = {
        "class": "d1",
        "expver": "0001",
        "stream": "oper",
        "dataset": "extremes-dt",
        "date": "-14",
        "time": "0000",
        "type": "fc",
        "levtype": "sfc",
        "step": "0",
        "param": "167",
        "grid": "H512"
    }
healpix_grid = earthkit.data.from_source("polytope", "destination-earth", request_healpix, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

In [23]:
healpix_grid.ls() # healpix

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,2t,heightAboveGround,2,20250813,0,0,fc,None,healpix

Client side regridding with Earthkit Data

In [33]:
import earthkit.regrid

In [44]:
request = {
    'activity': 'ScenarioMIP',
    'class': 'd1',
    'dataset': 'climate-dt',
    'date': '20200102',
    'experiment': 'SSP3-7.0',
    'expver': '0001',
    'generation': '1',
    'levtype': 'sfc',
    'model': 'IFS-NEMO',
    'param': '134',
    'realization': '1',
    'resolution': 'standard',
    'stream': 'clte',
    'time': '0100', # '0100/0200/0300/0400/0500/0600'
    'type': 'fc'
}

In [45]:
data = earthkit.data.from_source("polytope", "destination-earth", request, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

2025-08-27 19:04:34 - INFO - Key read from /Users/maes/.polytopeapirc
2025-08-27 19:04:34 - INFO - Sending request...
{'request': 'activity: ScenarioMIP\n'
            'class: d1\n'
            'dataset: climate-dt\n'
            "date: '20200102'\n"
            'experiment: SSP3-7.0\n'
            "expver: '0001'\n"
            "generation: '1'\n"
            'levtype: sfc\n'
            'model: IFS-NEMO\n'
            "param: '134'\n"
            "realization: '1'\n"
            'resolution: standard\n'
            'stream: clte\n'
            "time: '0100'\n"
            'type: fc\n',
 'verb': 'retrieve'}
2025-08-27 19:04:34 - INFO - Polytope user key found in session cache for user maes

2025-08-27 19:04:35 - INFO - Request accepted. Please poll ./7aef8418-ad48-434e-97fd-c6893fc374a9 for status
2025-08-27 19:04:35 - INFO - Polytope user key found in session cache for user maes
2025-08-27 19:04:35 - INFO - Checking request status (7aef8418-ad48-434e-97fd-c6893fc374a9)...
2025-08-27 19:04:35 - INFO - The current status of the request is 'queued'
2025-08-27 19:04:36 - INFO - The current status of the request is 'processing'
2025-08-27 19:04:50 - WARNING - Recovering from connection error.
HTTPSConnectionPool(host='download-polytope.lumi.apps.dte.destination-earth.eu', port=443): Max retries exceeded with url: /default/7aef8418-ad48-434e-97fd-c6893fc374a9.grib (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x166e24cd0>, 'Connection to download-polytope.lumi.apps.dte.destination-earth.eu timed out. (connect timeout=None)'))
2025-08-27 19:04:50 - INFO - Attempt 1 of 10
2025-08-27 19:04:50 - INFO - Next retry in 120 seconds
2025-08-27 19:06:51 - INFO - The current status of the request is 'processed'
Recovering from connection error [HTTPSConnectionPool(host='download-polytope.lumi.apps.dte.destination-earth.eu', port=443): Max retries exceeded with url: /default/7aef8418-ad48-434e-97fd-c6893fc374a9.grib (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x166e25090>, 'Connection to download-polytope.lumi.apps.dte.destination-earth.eu timed out. (connect timeout=30)'))], attempt 1 of 500
Retrying in 120 seconds
Recovering from connection error [HTTPSConnectionPool(host='download-polytope.lumi.apps.dte.destination-earth.eu', port=443): Max retries exceeded with url: /default/7aef8418-ad48-434e-97fd-c6893fc374a9.grib (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x166e251d0>, 'Connection to download-polytope.lumi.apps.dte.destination-earth.eu timed out. (connect timeout=30)'))], attempt 2 of 500
Retrying in 120 seconds
Recovering from connection error [HTTPSConnectionPool(host='download-polytope.lumi.apps.dte.destination-earth.eu', port=443): Max retries exceeded with url: /default/7aef8418-ad48-434e-97fd-c6893fc374a9.grib (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x166e24a50>, 'Connection to download-polytope.lumi.apps.dte.destination-earth.eu timed out. (connect timeout=30)'))], attempt 3 of 500
Retrying in 120 seconds

In [46]:
data.ls() # healpix grid

,centre,shortName,typeOfLevel,level,dataDate,dataTime,stepRange,dataType,number,gridType
0,ecmf,sp,surface,0,20200102,100,0,fc,None,healpix

In [47]:
# regrid to 1x1 degree
out_grid = {"grid": [1,1]}
data_interpolated = earthkit.regrid.interpolate(data, out_grid=out_grid, method="linear")

In [ ]:
data_interpolated.ls() # now on regular lat lon grid

In [11]:
import earthkit.data

request_original = {
        "class": "d1",
        "expver": "0001",
        "stream": "oper",
        "dataset": "extremes-dt",
        "date": "-14",
        "time": "0000",
        "type": "fc",
        "levtype": "sfc",
        "step": "13",
        "param": "167",
        # "feature" : {
        # "type" : "boundingbox",
        # "points" : [[30, -15], [75, 42]],
        # "axes" : ["latitude", "longitude"]
        # },
        "area": "75/-15/30/42.5",
        "grid": "0.01/0.01"
    }
original_grid = earthkit.data.from_source("polytope", "destination-earth", request_original, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

DEBUG:polytope.api.Client.1CED99:Gathered Polytope client configuration:
{'address': 'polytope.lumi.apps.dte.destination-earth.eu',
 'insecure': False,
 'key_path': PosixPath('/Users/maes/.polytopeapirc'),
 'log_file': None,
 'log_level': 'DEBUG',
 'password': None,
 'port': None,
 'quiet': False,
 'skip_tls': False,
 'user_email': None,
 'user_key': None,
 'username': 'maes',
 'verbose': False}
DEBUG:polytope.api.Client.1CED99:Creating Polytope client...
2025-09-01 13:52:35 - INFO - Key read from /Users/maes/.polytopeapirc
INFO:polytope.api.Client.1CED99:Key read from /Users/maes/.polytopeapirc
2025-09-01 13:52:35 - INFO - Sending request...
{'request': 'area: 75/-15/30/42.5\n'
            'class: d1\n'
            'dataset: extremes-dt\n'
            "date: '-14'\n"
            "expver: '0001'\n"
            'grid: 0.01/0.01\n'
            'levtype: sfc\n'
            "param: '167'\n"
            "step: '13'\n"
            'stream: oper\n'
            "time: '0000'\n"
            'type: fc\n',
 'verb': 'retrieve'}
INFO:polytope.api.Client.1CED99:Sending request...
{'request': 'area: 75/-15/30/42.5\n'
            'class: d1\n'
            'dataset: extremes-dt\n'
            "date: '-14'\n"
            "expver: '0001'\n"
            'grid: 0.01/0.01\n'
            'levtype: sfc\n'
            "param: '167'\n"
            "step: '13'\n"
            'stream: oper\n'
            "time: '0000'\n"
            'type: fc\n',
 'verb': 'retrieve'}
2025-09-01 13:52:35 - INFO - Polytope user key found in session cache for user maes
INFO:polytope.api.Client.1CED99:Polytope user key found in session cache for user maes
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP POST https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/destination-earth
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': {'verb': 'retrieve', 'request': "area: 75/-15/30/42.5\nclass: d1\ndataset: extremes-dt\ndate: '-14'\nexpver: '0001'\ngrid: 0.01/0.01\nlevtype: sfc\nparam: '167'\nstep: '13'\nstream: oper\ntime: '0000'\ntype: fc\n"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): polytope.lumi.apps.dte.destination-earth.eu:443
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "POST /api/v1/requests/destination-earth HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
2025-09-01 13:52:36 - INFO - Request accepted. Please poll ./56d5adeb-4c1e-4993-88b3-61070f8592b0 for status
INFO:polytope.api.Client.1CED99:Request accepted. Please poll ./56d5adeb-4c1e-4993-88b3-61070f8592b0 for status
DEBUG:polytope.api.Client.1CED99:Server message: Request queued
2025-09-01 13:52:36 - INFO - Polytope user key found in session cache for user maes
INFO:polytope.api.Client.1CED99:Polytope user key found in session cache for user maes
2025-09-01 13:52:36 - INFO - Checking request status (56d5adeb-4c1e-4993-88b3-61070f8592b0)...
INFO:polytope.api.Client.1CED99:Checking request status (56d5adeb-4c1e-4993-88b3-61070f8592b0)...
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): polytope.lumi.apps.dte.destination-earth.eu:443
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
2025-09-01 13:52:37 - INFO - The current status of the request is 'queued'
INFO:polytope.api.Client.1CED99:The current status of the request is 'queued'
DEBUG:polytope.api.Client.1CED99:Server message: Request queued
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
2025-09-01 13:52:38 - INFO - The current status of the request is 'processing'
INFO:polytope.api.Client.1CED99:The current status of the request is 'processing'
DEBUG:polytope.api.Client.1CED99:Server message: Request processing
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.1CED99:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.1CED99:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/56d5adeb-4c1e-4993-88b3-61070f8592b0 HTTP/1.1" 202 57

In [12]:
data = original_grid.to_xarray()
data['2t']

<xarray.DataArray '2t' (latitude: 4501, longitude: 5751)> Size: 207MB
[25885251 values with dtype=float64]
Coordinates:
  * latitude   (latitude) float64 36kB 75.0 74.99 74.98 ... 30.02 30.01 30.0
  * longitude  (longitude) float64 46kB -15.0 -14.99 -14.98 ... 42.48 42.49 42.5
Attributes:
    standard_name:  air_temperature
    long_name:      2 metre temperature
    units:          K
    _earthkit:      {'message': b'GRIB\xff\xff\x00\x02\x00\x00\x00\x00\x00\x0...

In [13]:
data['2t'].max() - 273.15

<xarray.DataArray '2t' ()> Size: 8B
array(45.8306633)

In [14]:
import earthkit.plots

chart = earthkit.plots.Map(domain=["Spain"])

chart.grid_cells(data['2t'],
    x="longitude",
    y="latitude",
    units="celsius", levels=range(0, 40, 5), colors="bwr",
)

chart.title()
chart.legend()
chart.cities()
chart.gridlines()
chart.coastlines()
chart.ocean(color="black")

chart.show()

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5751 and the array at index 1 has size 4501

Scenario MIP

In [17]:
request = {
    'activity': 'ScenarioMIP',
    'class': 'd1',
    'dataset': 'climate-dt',
    'date': '20260101',
    'experiment': 'SSP3-7.0',
    'expver': '0001',
    'generation': '1',
    'levtype': 'sfc',
    'model': 'IFS-NEMO',
    'param': '134',
    'realization': '1',
    'resolution': 'standard',
    'stream': 'clte',
    'time': '0000', # '0100/0200/0300/0400/0500/0600'
    'type': 'fc'
}
scenario_mip = earthkit.data.from_source("polytope", "destination-earth", request, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

DEBUG:polytope.api.Client.C0CNBS:Gathered Polytope client configuration:
{'address': 'polytope.lumi.apps.dte.destination-earth.eu',
 'insecure': False,
 'key_path': PosixPath('/Users/maes/.polytopeapirc'),
 'log_file': None,
 'log_level': 'DEBUG',
 'password': None,
 'port': None,
 'quiet': False,
 'skip_tls': False,
 'user_email': None,
 'user_key': None,
 'username': 'maes',
 'verbose': False}
DEBUG:polytope.api.Client.C0CNBS:Creating Polytope client...
2025-09-03 17:21:08 - INFO - Key read from /Users/maes/.polytopeapirc
INFO:polytope.api.Client.C0CNBS:Key read from /Users/maes/.polytopeapirc
2025-09-03 17:21:08 - INFO - Sending request...
{'request': 'area: 75/-15/30/42.5\n'
            'class: d1\n'
            'dataset: extremes-dt\n'
            "date: '-14'\n"
            "expver: '0001'\n"
            'grid: 0.01/0.01\n'
            'levtype: sfc\n'
            "param: '167'\n"
            "step: '13'\n"
            'stream: oper\n'
            "time: '0000'\n"
            'type: fc\n',
 'verb': 'retrieve'}
INFO:polytope.api.Client.C0CNBS:Sending request...
{'request': 'area: 75/-15/30/42.5\n'
            'class: d1\n'
            'dataset: extremes-dt\n'
            "date: '-14'\n"
            "expver: '0001'\n"
            'grid: 0.01/0.01\n'
            'levtype: sfc\n'
            "param: '167'\n"
            "step: '13'\n"
            'stream: oper\n'
            "time: '0000'\n"
            'type: fc\n',
 'verb': 'retrieve'}
2025-09-03 17:21:08 - INFO - Polytope user key found in session cache for user maes
INFO:polytope.api.Client.C0CNBS:Polytope user key found in session cache for user maes
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP POST https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/destination-earth
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': {'verb': 'retrieve', 'request': "area: 75/-15/30/42.5\nclass: d1\ndataset: extremes-dt\ndate: '-14'\nexpver: '0001'\ngrid: 0.01/0.01\nlevtype: sfc\nparam: '167'\nstep: '13'\nstream: oper\ntime: '0000'\ntype: fc\n"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): polytope.lumi.apps.dte.destination-earth.eu:443
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "POST /api/v1/requests/destination-earth HTTP/1.1" 202 49
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
2025-09-03 17:21:10 - INFO - Request accepted. Please poll ./83c60fa5-5d69-4f59-af16-079a0d2b7334 for status
INFO:polytope.api.Client.C0CNBS:Request accepted. Please poll ./83c60fa5-5d69-4f59-af16-079a0d2b7334 for status
DEBUG:polytope.api.Client.C0CNBS:Server message: Request queued
2025-09-03 17:21:10 - INFO - Polytope user key found in session cache for user maes
INFO:polytope.api.Client.C0CNBS:Polytope user key found in session cache for user maes
2025-09-03 17:21:10 - INFO - Checking request status (83c60fa5-5d69-4f59-af16-079a0d2b7334)...
INFO:polytope.api.Client.C0CNBS:Checking request status (83c60fa5-5d69-4f59-af16-079a0d2b7334)...
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): polytope.lumi.apps.dte.destination-earth.eu:443
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
2025-09-03 17:21:10 - INFO - The current status of the request is 'queued'
INFO:polytope.api.Client.C0CNBS:The current status of the request is 'queued'
DEBUG:polytope.api.Client.C0CNBS:Server message: Request queued
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 49
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
2025-09-03 17:21:10 - INFO - The current status of the request is 'processing'
INFO:polytope.api.Client.C0CNBS:The current status of the request is 'processing'
DEBUG:polytope.api.Client.C0CNBS:Server message: Request processing
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57
DEBUG:polytope.api.Client.C0CNBS:Polytope client received HTTP SUCCESS (202)
DEBUG:polytope.api.Client.C0CNBS:Polytope client attempting HTTP GET https://polytope.lumi.apps.dte.destination-earth.eu:443/api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334
{'headers': {'Authorization': 'EmailKey alice.sartorimonteirodebarros@ecmwf.int:363426240837884ba53945ec749c35fd'}, 'json': None}
DEBUG:urllib3.connectionpool:https://polytope.lumi.apps.dte.destination-earth.eu:443 "GET /api/v1/requests/83c60fa5-5d69-4f59-af16-079a0d2b7334 HTTP/1.1" 202 57

In [ ]:
request = {
    'activity': 'CMIP6',
    'class': 'd1',
    'dataset': 'climate-dt',
    'date': '20020101',
    'experiment': 'hist',
    'expver': '0001',
    'generation': '1',
    'levtype': 'sfc',
    'model': 'IFS-NEMO',
    'param': '134',
    'realization': '1',
    'resolution': 'standard',
    'stream': 'clte',
    'time': '0000',
    'type': 'fc'
}
cmip6 = earthkit.data.from_source("polytope", "destination-earth", request_original, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

In [ ]:
request = {
    'activity': 'HighResMip',
    'class': 'd1',
    'dataset': 'climate-dt',
    'date': '20020101',
    'experiment': 'cont',
    'expver': '0001',
    'generation': '1',
    'levtype': 'sfc',
    'model': 'IFS-NEMO',
    'param': '134',
    'realization': '1',
    'resolution': 'standard',
    'stream': 'clte',
    'time': '0000',
    'type': 'fc'
}
hihgresmip = earthkit.data.from_source("polytope", "destination-earth", request_original, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)

In [ ]:
request = {
    'activity': 'story-nudging',
    'class': 'd1',
    'dataset': 'climate-dt',
    'date': '20250801',
    'experiment': 'cont',
    'expver': '0001',
    'generation': '1',
    'levtype': 'sfc',
    'model': 'IFS-FESOM',
    'param': '134',
    'realization': '1',
    'resolution': 'standard',
    'stream': 'clte',
    'time': '0000',
    'type': 'fc'
}
story_nudging = earthkit.data.from_source("polytope", "destination-earth", request_original, address="polytope.lumi.apps.dte.destination-earth.eu", stream=False)